spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/demorestful?characterEncoding=utf-8&useSSL=false
jpa:
    show-sql: true
    #懒加载异常处理
    #open-in-view: false
    #properties.hibernate.enable_lazy_load_no_trans: true
server:
  servlet:
    context-path: /demorestful